### ISSUE TITLE
Could not decode image: ISIC_0000003_Segmentation.png

### ISSUE THREAD

**Issue by NanditaDamaraju** [ImageMarkup/isic-challenge-scoring#13]
I keep getting this error. Could you provide more clarity on the submission format?

**Comment by brianhelba** [comment]
Thanks for the report @NanditaDamaraju . I've actually just corrected your issue, and we're waiting on our updated [Docker container to finish building](https://hub.docker.com/r/isic/isbi-challenge-scoring-auto/builds/) before the fix will be live.

I received your email about this issue before, I was going to (and still will) reply to it as soon it's safe to make a new submission.

Thanks again for the report and your participation.

**Comment by NanditaDamaraju** [comment]
Sure @brianhelba! Thanks for the quick response! Please do notify us once it's live :+1:

**Comment by brianhelba** [comment]
@NanditaDamaraju Just to confirm, the fix is live. Submit whenever you'd like.
