### ISSUE TITLE
Handle semicolon delimited CSV file

### ISSUE THREAD

**Issue by msmolens** [ImageMarkup/isic-challenge-scoring#14]
A possible solution is to use https://docs.python.org/2/library/csv.html#csv.Sniffer, as described here:
http://stackoverflow.com/questions/16312104/python-import-csv-file-delimiter-or

**Comment by sgratzl** [comment]
see also https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html ... 

```
sep : str, default ‘,’

    Delimiter to use. If sep is None, the C engine cannot automatically detect the separator, but the Python parsing engine can, meaning the latter will be used and automatically detect the separator by Python’s builtin sniffer tool, csv.Sniffer. In addition, separators longer than 1 character and different from '\s+' will be interpreted as regular expressions and will also force the use of the Python parsing engine. Note that regex delimiters are prone to ignoring quoted data. Regex example: '\r\t'.

```

**Comment by brianhelba** [comment]
@sgratzl Great suggestion, thanks.

**Comment by brianhelba** [comment]
I think we should close this as won't fix. For the sort of submitted CSVs that this parses, there should be no reason why accepting only comma-separated delimiters is burdensome to submitters, and forcing a stricter bound on submitted CSVs makes it easier for downstream analysis and simplifies testing and debugging of this library.
