### ISSUE TITLE
Always throws exception for test submission for tasks 1 or 2 

### ISSUE THREAD

**Issue by umasehs** [ImageMarkup/isic-challenge-scoring#57]
https://github.com/ImageMarkup/isic-challenge-scoring/blob/3392172482e175d06d207c4f6552a531157bfe3c/isic_challenge_scoring/__init__.py#L136

Currently, this always throws an exception when evaluating the test submissions for any task where task_num != 3 (i.e. tasks 1 or 2). This 'if' should probably be an 'elif'. I've submitted a PR addressing this issue (https://github.com/ImageMarkup/isic-challenge-scoring/pull/56).

**Comment by brianhelba** [comment]
Fixed by #56
