### ISSUE TITLE
Wrong pip install command in README

### ISSUE THREAD

**Issue by AlexandrosFerles** [ImageMarkup/isic-challenge-scoring#86]
In the pip install command in README file, you have used underscores for the pip package, which leads to a 'Package not found error' when installing. As in the [pypi](https://pypi.org/project/isic-challenge-scoring/) page, you can see that the correct command would be ```pip install isic-challenge-scoring```.

**Comment by brianhelba** [comment]
@AlexandrosFerles Thanks for your feedback. You can indeed use it both ways, but PyPI seems to prefer dashes for the canonical package names. I'll update the README.

**Comment by AlexandrosFerles** [comment]
Hi, I noticed that in another machine I could also use underscores (and that is why I closed my own issue), but in the general case dashes seem to work better, so thanks for updating the README file!
