### ISSUE TITLE
Can not install the module

### ISSUE THREAD

**Issue by masih4** [ImageMarkup/isic-challenge-scoring#89]
I tried to install this module with both `pip install isic-challenge-scoring` and `pip install isic_challenge_scoring` but got the following error: 

```
ERROR: Could not find a version that satisfies the requirement isic-challenge-scoring (from versions: none)
ERROR: No matching distribution found for isic-challenge-scoring

```

I am wondering if you could help me.

**Comment by brianhelba** [comment]
Hi @masih4 ,

I'm not sure what's happening. Pip should be able to resolve this package: https://pypi.org/project/isic-challenge-scoring/

Is it possibly something with your network or your Pip's default package index? Are you able to reproduce this on another machine or in a fresh virtualenv? Are you able to install other pip packages successfully from PyPI?

**Comment by masih4** [comment]
Dear @brianhelba 
Thank you for your quick response. I just noted that it needs python 3.7+ and I am using 3.6.8 and probably that is the problem?
Is there any get around to make it work with python 3.6?

**Comment by brianhelba** [comment]
Hi @masih4 ,

Yes, the code here uses both [dataclasses](https://docs.python.org/3/whatsnew/3.7.html#dataclasses) and [Postponed Evaluation of Annotations](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations), so it needs Python 3.7.

You can use [pyenv](https://github.com/pyenv/pyenv) to install Python 3.7 on your system as an additional version.

Alternatively, we package this library for CLI execution via Docker, and you could run it that way to not worry about Python at all. ~~Of course, the documentation on how to use it via Docker needs to be improved somewhat~~.

**Comment by brianhelba** [comment]
Hi again @masih4 ,

Thanks for bringing up these issues. To make things easier for yourself and other users, I've explicitly documented the minimum Python version and instructions for running the CLI via Docker.

This should resolve this issue as best I can. Feel free to open other issues if you have other problems or suggestions.
